<article>
    <h1>Search for People at UC Merced</h1>
    <p class="disclaimer"><em>Notice: This campus directory has been compiled for the use and convenience of the faculty, staff and students of the University of California, Merced and others dealing with UC Merced. It is the property of the Regents of the University of California. Neither this directory nor the information contained herein may be used, rented, distributed, or sold for commercial purposes in accordance with the California Information Practices Act.</em></p>
</article>
<aside>
    <h3>Searching Tips</h3>
    <ul>
        <li>Use this page to search for faculty, staff, affiliates or students at UC Merced.</li>
        <li>To find departmental contact information, please select <a href="department.cfm">Departments</a> from the grey bar at the top of this page.</li>
        <li>Select which field you would like to search by from the drop down list and enter your search phrase in the search box.</li>
        <li>All matching results will be returned.</li>
        <li>This search supports partial names. For example, entering &quot;rob&quot; will find people named robert, robertson, robin, etc.</li>
    </ul>
</aside>