<div id="searchResults">
<article>
    <?php echo $this->displayErrors() ?>
    <?php echo $this->displayMsg() ?>
    <h1>Search for People at UC Merced</h1>
    <?php echo $this->searchForm?>
</article>
<?php if($this->searched){ ?>
    <article>
        <?php if($this->searchResults){ ?>
            <h1>Search Results</h1>
            <ul class="searchResults">
                <?php echo $this->partialLoop()->setObjectKey('person')
                        ->partialLoop("partials/searchListing.phtml",$this->searchResults) ?>
            </ul>
        <?php }
        else{ ?>
            <p class='error'>No Results Found</p>
        <?php } ?>
    </article>
<?php } ?>
<?php echo $this->getDisclaimer()?>
</div>
<?php echo $this->partial("partials/SidePeopleSearch.phtml"); ?>