<div data-role="collapsible" data-iconpos="right" data-content-theme="c">
    <h3><?php echo $this->person->lastName . ", " . $this->person->firstName?></h3>
    <p class="searchResults">
        <?php echo  $this->getJobTitle($this->person);?><br />
        <?php if(!empty($this->person->email)) echo "<span class='email'><a href='mailto:" . $this->person->email . "'>" . $this->person->email . "</a></span><br />"?>
        <?php if(!empty($this->person->phone)) echo "<span class='phone'>Phone:</span>" . $this->phoneFormat($this->person->phone) . "<br />"?>
        <?php if(!empty($this->person->fax)) echo "<span class='fax'>Fax:</span>" . $this->phoneFormat($this->person->fax) . "<br />"?>
        <?php if(!empty($this->person->cellPhone)) echo "<span class='mobile'>Mobile:</span>" . $this->phoneFormat($this->person->cellPhone) . ""?>
    </p>
    <div data-role="collapsible" data-iconpos="right" data-content-theme="c">
        <h3>Download Contact</h3>
        <p>Enter an email address accessible by your phone and we'll send this contact to you.</p>
        <form action="/mobile/print/contact" method="post" class="sendContactForm" name="sendContact<?php echo $this->partialCounter?>">
            <label>Email:</label>
            <input type="text" name="email" class="email" />
            <input type="submit" name="submit" value="Go" />
        </form>
    </div>
</div>