<ul id="deptSearchResult" class="searchResults">
    <li>
        <div class="left">
            <h2><?php echo $this->department->getName()?></h2>
            <?php if(!empty($this->department->description)){ ?>
            <p>
                <?php echo $this->department->getDescription()?><br />
            </p>
            <?php } ?>
        </div>
        <div class="right">
            <?php if(!empty($this->department->phone)) echo "<span class='phone'>Phone:</span>" . $this->phoneFormat($this->department->phone) . "<br />"?>
            <?php if(!empty($this->department->fax)) echo "<span class='fax'>Fax:</span>" . $this->phoneFormat($this->department->fax) . "<br />"?>
            <?php if(!empty($this->department->url)) echo "<span class='url'><a href='" .$this->department->url . "' target='_blank' title='" . $this->department->url . "'>Visit Website</a></span>" ?>
        </div>
    </li>
</ul>