
        <li <?php if($this->partialCounter % 2==0) echo "class='alt'"?>>
            <div class="left">
                <a href="<?php echo $this->getDetailsLink($this->person)?>"  class="name"><?php echo $this->person->getLastNameFirst()?></a><br />
                <?php echo $this->getJobTitle($this->person);?>
            </div>
            <div class="right">
                <?php if(!empty($this->person->email)) echo "<span class='email'><a href='mailto:" . $this->person->email . "'>" . $this->person->email . "</a></span><br />"?>
                <?php if($this->person->getPrimaryAffiliation()!="student"){ ?>
                    <?php if(!empty($this->person->phone)) echo "<span class='phone'>Phone:</span>" . $this->phoneFormat($this->person->phone) . "<br />"?>
                    <?php if(!empty($this->person->fax)) echo "<span class='fax'>Fax:</span>" . $this->phoneFormat($this->person->fax) . "<br />"?>
                    <?php if(!empty($this->person->cellPhone)) echo "<span class='mobile'>Mobile:</span>" . $this->phoneFormat($this->person->cellPhone) . ""?>
               <?php } ?>
            </div>
        </li>
