<div data-role="collapsible" data-iconpos="right" data-content-theme="c">
    <h3><?php echo $this->person->lastName . ", " . $this->person->firstName?></h3>
    <p class="searchResults">
        <?php echo  $this->getJobTitle($this->person);?><br />
        <?php if(!empty($this->person->email)) echo "<span class='email'><a href='mailto:" . $this->person->email . "'>" . $this->person->email . "</a></span><br />"?>
        <?php if(!empty($this->person->phone)) echo "<span class='phone'>Phone:</span><a href='tel://1" . $this->person->phone . "'>" . $this->phoneFormat($this->person->phone) . "</a><br />"?>
        <?php if(!empty($this->person->fax)) echo "<span class='fax'>Fax:</span>" . $this->phoneFormat($this->person->fax) . "<br />"?>
        <?php if(!empty($this->person->cellPhone)) echo "<span class='mobile'>Mobile:</span><a href='tel://1" . $this->phoneFormat($this->person->cellPhone) . "'>" . $this->phoneFormat($this->person->cellPhone) . "</a>"?>
    </p>
    <div data-role="collapsible" data-iconpos="right" data-content-theme="c">
        <h3>Download Contact</h3>
        <p>Enter an email address accessible by your phone and we'll send this contact to you.</p>
        <form action="/site/email/sendcontact" method="post" class="sendContactForm" name="sendContact<?php echo $this->partialCounter?>" data-ajax="false">
            <label>Email:</label>
            <input type="hidden" name="email" class="email" value="<?php echo $this->person->getEmail()?>" />
            <input type="text" name="sendTo" class="sendTo" />
            <input type="submit" name="submit" value="Go" />
        </form>
    </div>
</div>