<aside>
    <h3>Searching Tips</h3>
    <ul>
        <li>Use this page to search for departments at UC Merced.</li>
        <li>Either select a department from the drop down list or click on a department name from the list below.</li>
        <li>All matching results will be returned.</li>
        <li>We have a mobile version! <a href="/redirect/mobile">Visit Mobile Version</a></li>
    </ul>
</aside>
