<aside>
    <h3>Searching Tips</h3>
    <ul>
        <li>Use this page to search for faculty, staff, affiliates or students at UC Merced.</li>
        <li>To find departmental contact information, please select <a href="/site/departments">Departments</a> from the grey bar at the top of this page.</li>
        <li>Select which field you would like to search by from the drop down list and enter your search phrase in the search box.</li>
        <li>All matching results will be returned.</li>
        <li>This search supports partial names. For example, entering &quot;rob&quot; will find people named robert, robertson, robin, etc.</li>
        <li>We have a mobile version! <a href="/redirect/mobile">Visit Mobile Version</a></li>
        <?php
            $policeMsg=$this->displayPoliceStatus();
            if(!empty($policeMsg)){
                echo "<li>" . $policeMsg . "</li>";
            }
        ?>
    </ul>
</aside>