<aside>
    <h3>Contact Tips</h3>
    <ul>
        <li>Click on <strong>People</strong> in the top grey bar to start a <a href="/">new search</a>.</li>
        <li>To go back to your search results, use your browser's back button.</li>
        <li>Download this individual's vCard to easily import their contact information into Outlook, Thunderbird, Mac OS X Address Book, or any other program that supports the vCard format.</li>
        <li>To find departmental contact information, please select <a href="#">Departments</a> from the grey bar at the top of this page.</li>
    </ul>
</aside>