<aside>

    <h3>Updating Information</h3>
    <ul>
            <li>Modify the information you would like to change.</li>
            <li>Select your MSO from the pull down list.</li>
            <li>An email will be sent to your MSO with your request.</li>
            <li>Once approved, the IDM office will update your information</li>
            <li>If you don't want to update information, <a href="/site/help/logout">please click here to logout of CAS</a></li>
    </ul>


</aside>