<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<?php

            $title=$this->headTitle();
            if($title=="<title></title>"){
                echo "<title>UC Merced People Directory</title>";
            }
            else{
                echo $title;
            }
         ?>



	<meta name="description" content="">
	<meta name="author" content="">

        <link rel="apple-touch-icon" href="apple-touch-icon.png" />
	<link type="text/css" rel="stylesheet" href="/min/f=css/style_1.css" />

        <?php echo $this->headLink();?>
        <?php echo $this->headStyle();?>

</head>
<body>

<div id="container">
	<header>
            <a href="http://www.ucmerced.edu" target="_blank" style='display:block; width:270px; height:62px; position:absolute;'></a>
            <nav>
                <a href="/" <?php if($this->page=="people") echo "class='active'"?>>People</a>
                <a href="/site/departments" <?php if($this->page=="dept") echo "class='active'"?>>Departments</a>
                <a href="http://www.ucmerced.edu" target="_blank">UC Merced Home</a>
            </nav>
	</header>
	<div id="main" role="main">
            <?php echo $this->layout()->content; ?>
	</div>
	<footer>
            University of California, Merced | 5200 North Lake Rd, Merced, CA 95343 | (209) 228-4400 | &copy; <?php echo date("Y");?> UC Regents
            &nbsp; - &nbsp;<a href="http://www.ucmerced.edu/privacy-statement" target="_blank">Privacy/Legal Notice</a>
	</footer>
        <script src="http://code.jquery.com/jquery-1.7.1.js"></script>
        <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.1.min.js"><\/script>')</script>
         <?php echo $this->headScript();?>
        <script type="text/javascript" src="/min/f=js/script.js"></script>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-28206564-1']);
          _gaq.push(['_setDomainName', 'ucmerced.edu']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
</div> <!--! end of #container -->


</body>
</html>


