<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<?php echo $this->headTitle() ?>
	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png" />

	<link rel="stylesheet" href="/css/style.css">

        <script src="http://code.jquery.com/jquery-1.7.1.js"></script>
        <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.1.min.js"><\/script>')</script>

	<script src="/js/libs/modernizr-2.0.6.min.js"></script>
        <script src="/js/script.js"></script>
        <?php echo $this->headLink();?>
        <?php echo $this->headStyle();?>
        <?php echo $this->headScript();?>
</head>
<body>

<div id="container">
	<header>
            <nav>
                <a href="/" <?php if($this->page=="people") echo "class='active'"?>>People</a>
                <a href="/site/departments" <?php if($this->page=="dept") echo "class='active'"?>>Departments</a>
                <a href="http://www.ucmerced.edu" target="_blank">UC Merced Home</a>
            </nav>
	</header>
	<div id="main" role="main">
            <?php echo $this->layout()->content; ?>
	</div>
	<footer>
            University of California, Merced | 5200 North Lake Rd, Merced, CA 95343 | (209) 228-4400 | &copy; 2008 UC Regents
            &nbsp; - &nbsp;<a href="http://www.ucmerced.edu/privacy-statement" target="_blank">Privacy/Legal Notice</a>
	</footer>
</div> <!--! end of #container -->


</body>
</html>


