<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>

        <?php echo $this->headTitle() ?>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">

        <link rel="stylesheet" href="/css/mobile.css" />

        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0-rc.2/jquery.mobile-1.1.0-rc.2.min.css" />
        <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="/js/mobile.js"></script>
        <script src="http://code.jquery.com/mobile/1.1.0-rc.2/jquery.mobile-1.1.0-rc.2.min.js"></script>





        <?php echo $this->headLink();?>
        <?php echo $this->headStyle();?>
        <?php echo $this->headScript();?>

    </head>
    <body>
        <div data-role="page" data-add-back-btn="true" data-back-btn-text="&nbsp;" <?php if(isset($this->pageDataAttributes)) echo $this->pageDataAttributes?>>
            <div data-role="header" data-theme="b" data-position="fixed"><span class="hdrImg"><img src="/images/mobile/logo.png" alt="UC Merced Directory" /></span></div>

            <div data-role="content">
                <?php echo $this->layout()->content; ?>
            </div>

            <div data-role="footer" data-theme="b" data-position="fixed">
                <div data-role="controlgroup" data-type="horizontal">
                    <a href="/site/index/" class="people border-right">People</a>
                    <a href="/site/departments/" class="departments">Departments</a>
                    <a href="/site/help/" class="help">Help</a>
                </div>
            </div>

        </div>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-30657753-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
    </body>
</html>

