<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<?php echo $this->headTitle() ?>
	<meta name="description" content="">
	<meta name="author" content="">

</head>
<body>
<link type="text/css" rel="stylesheet" href="/min/f=css/style_1.css" />
<?php echo $this->headLink();?>
<?php echo $this->headStyle();?>
<div id="container">

	<div id="main" role="main">
            <?php echo $this->layout()->content; ?>
	</div>
        <script src="http://code.jquery.com/jquery-1.7.1.js"></script>
        <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.1.min.js"><\/script>')</script>
         <?php echo $this->headScript();?>
        <script type="text/javascript" src="/min/f=js/script.js"></script>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-30657753-1']);
          _gaq.push(['_setCustomVar', 1, 'View', 'Portal', 2]);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
</div> <!--! end of #container -->


</body>
</html>


