<div class="innerContentItem ui-corner-all ui-shadow">
    <h3>People Search:</h3>
    <ul>
        <li>Use this page to search for faculty, staff, affiliates or students at UC Merced. </li>
        <li>To find departmental contact information, please select Departments from the blue bar at the bottom of this page. </li>
        <li>Select which field you would like to search by from the drop down list and enter your search phrase in the search box.</li>
        <li>All matching results will be returned. </li>
        <li>This search supports partial names. For example, entering "rob" will find people named robert, robertson, robin, etc. </li>
    </ul>
</div>

<div class="innerContentItem ui-corner-all ui-shadow">
    <h3>Department Search:</h3>
    <ul>
        <li>Use this page to search for departments at UC Merced.</li>
        <li>Either select a department from the drop down list or click on a department name from the list below.</li>
        <li>All matching results will be returned.</li>
    </ul>
</div>

<ul data-inset="true" data-role="listview">
    <li><a href="/help/contact">Contact Us</a></li>
</ul>