<div data-role="header" data-theme="b">
    <h1><?php echo $this->dept->getName();?></h1>
</div>

<div data-role="content">
    <?php if($this->searchResults){ ?>
        <?php if(!empty($this->dept->description)){ ?>
        <div class="innerContentItem ui-corner-all ui-shadow">
            <?php echo $this->dept->getDescription()?>
        </div>
        <?php } ?>
        <div class="innerContentItem ui-corner-all ui-shadow">
            <?php if(!empty($this->dept->phone)) echo "<span class='phone'>Phone:</span><a href='tel://1" . $this->phoneFormat($this->dept->phone) . "'>" . $this->phoneFormat($this->dept->phone) . "</a><br />"?>
            <?php if(!empty($this->dept->fax)) echo "<span class='fax'>Fax:</span>" . $this->phoneFormat($this->dept->fax) . "<br />"?>
            <?php if(!empty($this->dept->url)) echo "<span class='url'><a href='" .$this->dept->url . "' target='_blank' title='" . $this->dept->url . "'>Visit Website</a></span>" ?>
        </div>
    <?php }
    else { ?>
        <div class="innerContentItem ui-corner-all ui-shadow">Sorry, there doesn't seem to be any info on this department.</div>
    <?php } ?>
    <ul data-inset="true" data-role="listview">
        <li><a href="mailto:idm@ucmerced.edu">Is this data wrong? Email us</a></li>
    </ul>
</div>

