<html><body>
<center><h1>UC Merced Directory</h1></center>
<p>
    <strong><?php echo $this->search?></strong><br />
    Search By: <?php echo $this->escape($this->searchBy)?><br />
    Search For: <?php echo $this->escape($this->searchFor)?><br />
</p>

<p><strong>Search Results</strong></p>
<hr />
<?php if($this->searchResults){ ?>
<table cellspacing="0" cellpadding="0" width="100%">
        <?php
        $count=0;
        foreach($this->searchResults as $result){?>
            <tr <?php if($count % 2 == 0) echo "bgcolor='EEEEEE'"?>>
                <td style="padding: 10px 0px" valign="top" width="80%">
                    <?php echo $result->getLastNameFirst() ?><br>
                    <?php echo $this->getJobTitle($result); ?>
                </td>
                <td align="left" valign="top" width="20%" style="padding: 10px 0px">
                    <?php echo $result->getEmail()?><br />
                    <?php if(!empty($result->phone)) echo "W: " . $this->phoneFormat($result->phone) . "<br />" ?>
                    <?php if(!empty($result->fax)) echo "F: " . $this->phoneFormat($result->fax) . "<br />" ?>
                    <?php if(!empty($result->cellPhone)) echo "M: " . $this->phoneFormat($result->cellPhone) ?><br />
                </td>
            </tr>
        <?php
            $count++;
        } ?>
</table>
<?php }
else{ ?>
<p><strong>No Results Found</strong></p>
<?php } ?>
</body></html>

